name: 'JS Tests'
on:
  pull_request:
    paths:
      - 'tests/js/**'
      - 'ui/js/**'
      - 'package.json'
      - 'webpack.*.js'
      - 'jest-setup-wordpress-globals.js'
      - 'jest.config.json'
      - '.github/workflows/tests-js.yml'
jobs:
  test:
    strategy:
      matrix:
        suite: [ 'test-dfv', 'jest-tests' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install
      - name: Run JS test suite
        run: npm run ${{ matrix.suite }}