name: Deploy to WordPress.org
on: workflow_dispatch
  #release:
    #types: [published]
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - name: Check the version number from package.json
      shell: bash
      run: echo "PLUGIN_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@master
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        VERSION: ${{ env.PLUGIN_VERSION }}
    - name: Send message to Slack API
      uses: archive/github-actions-slack@v2.7.0
      id: notify
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
        slack-channel: C02SWND14
        slack-text: The ${{ github.event.repository.name }} tag has been deployed to svn.wordpress.org ðŸŽ‰
