name: "WordPress version checker"
on:
  push:
    branches:
      - main
      - release/*
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write

jobs:
  wordpress-version-checker:
    runs-on: ubuntu-latest
    steps:
      - name: WordPress version checker
        uses: skaut/wordpress-version-checker@v2.2.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
